apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-web
  labels:
    app: expenses-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expenses-web
  template:
    metadata:
      labels:
        app: expenses-web
    spec:
      containers:
        - name: api
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/expenses-api:TAG
          command: ["sh", "-c", "npx prisma migrate deploy && node dist/index.js"]
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: expenses-api-secrets
                  key: DATABASE_URL
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: expenses-api-secrets
                  key: ADMIN_JWT_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
